=== ratPoopert/csrc-scraper/tests/examples/cmvp/certificates/json/cmvp-certificate.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "CMVP Certificate",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "$schema": {
      "type": "string"
    },
    "Certificate Number": {
      "type": "string",
      "pattern": "^[0-9]+$"
    },
    "Details": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "Allowed Algorithms": {
          "type": "string"
        },
        "Entropy": {
          "type": "string"
        },
        "Module Name": {
          "type": "string"
        },
        "Standard": {
          "type": "string",
          "enum": [
            "FIPS 140-1",
            "FIPS 140-2",
            "FIPS 140-3"
          ]
        },
        "Status": {
          "type": "string",
          "enum": [
            "Active",
            "Historical",
            "Revoked"
          ]
        },
        "Sunset Date": {
          "type": "string"
        },
        "Historical Reason": {
          "type": "string"
        },
        "Overall Level": {
          "type": "integer",
          "enum": [
            1,
            2,
            3,
            4
          ]
        },
        "Caveat": {
          "type": "string"
        },
        "Security Level Exceptions": {
          "type": "array",
          "minItems": 1,
          "additionalItems": false,
          "items": {
            "type": "string"
          }
        },
        "Module Type": {
          "type": "string",
          "enum": [
            "Software",
            "Hardware"
          ]
        },
        "Embodiment": {
          "type": "string",
          "enum": [
            "Multi-chip embedded",
            "Multi-Chip Embedded",
            "Multi-chip standalone",
            "Single-chip",
            "Single Chip",
            "Multi-Chip Stand Alone"
          ]
        },
        "Description": {
          "type": "string"
        },
        "Tested Configuration(s)": {
          "type": "array",
          "minItems": 1,
          "additionalItems": false,
          "items": {
            "type": "string"
          }
        },
        "Approved Algorithms": {
          "type": "array",
          "minItems": 1,
          "additionalItems": false,
          "items": {
            "type": "array",
            "additionalItems": false,
            "items": [
              {
                "type": "string"
              },
              {
                "type": "string"
              },
              {
                "type": "array",
                "items": {
                  "type": "string",
                  "format": "uri"
                }
              }
            ]
          }
        },
        "Other Algorithms": {
          "type": "string"
        },
        "Software Versions": {
          "type": "string"
        },
        "Hardware Versions": {
          "type": "string"
        },
        "Firmware Versions": {
          "type": "string"
        },
        "Product URL": {
          "type": "string",
          "format": "uri"
        }
      },
      "required": [
        "Module Name",
        "Standard",
        "Status",
        "Overall Level",
        "Module Type",
        "Embodiment",
        "Description"
      ]
    },
    "Vendor": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "Name": {
          "type": "string"
        },
        "Website": {
          "type": "string",
          "format": "uri"
        },
        "Address": {
          "type": "string"
        },
        "Contacts": {
          "type": "array",
          "minLength": 1,
          "maxLength": 2,
          "items": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
              "Name": {
                "type": "string"
              },
              "Email": {
                "type": "string",
                "format": "email"
              },
              "Phone": {
                "type": "string"
              },
              "Fax": {
                "type": "string"
              }
            },
            "required": [
              "Name",
              "Email"
            ]
          }
        }
      },
      "required": [
        "Name",
        "Website",
        "Address",
        "Contacts"
      ]
    },
    "Related Files": {
      "type": "array",
      "additionalItems": false,
      "items": {
        "type": "array",
        "additionalItems": false,
        "items": [
          {
            "type": "string"
          },
          {
            "type": "string",
            "format": "uri"
          }
        ]
      }
    },
    "Validation History": {
      "type": "array",
      "minItems": 1,
      "additionalItems": false,
      "items": {
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "Date": {
            "type": "string"
          },
          "Type": {
            "type": "string",
            "enum": [
              "Initial",
              "Update"
            ]
          },
          "Lab": {
            "type": "string"
          }
        },
        "required": [
          "Date",
          "Type",
          "Lab"
        ]
      }
    }
  },
  "required": [
    "Certificate Number",
    "Details",
    "Vendor",
    "Related Files",
    "Validation History"
  ]
}

=== ratPoopert/csrc-scraper/tests/cmvp/json/3117.json
{
  "$schema": "./cmvp-certificate.schema.json",
  "Certificate Number": "3117",
  "Details": {
    "Module Name": "Brocade® X6-8 and X6-4 Directors",
    "Standard": "FIPS 140-2",
    "Status": "Historical",
    "Historical Reason": "SP 800-56Arev3 transition",
    "Overall Level": 2,
    "Caveat": "When operated in FIPS mode and when tamper evident labels are installed as indicated in the Security Policy. The module generates cryptographic keys whose strengths are modified by available entropy",
    "Security Level Exceptions": [
      "Mitigation of Other Attacks: N/A"
    ],
    "Module Type": "Hardware",
    "Embodiment": "Multi-Chip Stand Alone",
    "Description": "The Brocade® X6-8 and X6-4 directors provide a reliable, scalable Fibre Channel switching infrastructure with Gen 6 32 Gbps technology and capabilities that support demanding, enterprise-class private cloud storage and highly virtualized environments.",
    "Tested Configuration(s)": [
      "N/A"
    ],
    "Approved Algorithms": [
      [
        "AES",
        "Certs. #4116, #4145 and #4243",
        [
          "https://csrc.nist.gov/projects/Cryptographic-Algorithm-Validation-Program/details?source=AES&number=4116",
          "https://csrc.nist.gov/projects/Cryptographic-Algorithm-Validation-Program/details?source=AES&number=4145",
          "https://csrc.nist.gov/projects/Cryptographic-Algorithm-Validation-Program/details?source=AES&number=4243"
        ]
      ],
      [
        "CVL",
        "Certs. #923, #924, #990, #991 and #992",
        [
          "https://csrc.nist.gov/projects/Cryptographic-Algorithm-Validation-Program/details?source=Component&number=923",
          "https://csrc.nist.gov/projects/Cryptographic-Algorithm-Validation-Program/details?source=Component&number=924",
          "https://csrc.nist.gov/projects/Cryptographic-Algorithm-Validation-Program/details?source=Component&number=990",
          "https://csrc.nist.gov/projects/Cryptographic-Algorithm-Validation-Program/details?source=Component&number=991",
          "https://csrc.nist.gov/projects/Cryptographic-Algorithm-Validation-Program/details?source=Component&number=992"
        ]
      ],
      [
        "DRBG",
        "Certs. #1239 and #1322",
        [
          "https://csrc.nist.gov/projects/Cryptographic-Algorithm-Validation-Program/details?source=DRBG&number=1239",
          "https://csrc.nist.gov/projects/Cryptographic-Algorithm-Validation-Program/details?source=DRBG&number=1322"
        ]
      ],
      [
        "DSA",
        "Cert. #1133",
        [
          "https://csrc.nist.gov/projects/Cryptographic-Algorithm-Validation-Program/details?source=DSA&number=1133"
        ]
      ],
      [
        "ECDSA",
        "Certs. #934 and #983",
        [
          "https://csrc.nist.gov/projects/Cryptographic-Algorithm-Validation-Program/details?source=ECDSA&number=934",
          "https://csrc.nist.gov/projects/Cryptographic-Algorithm-Validation-Program/details?source=ECDSA&number=983"
        ]
      ],
      [
        "HMAC",
        "Certs. #2688 and #2781",
        [
          "https://csrc.nist.gov/projects/Cryptographic-Algorithm-Validation-Program/details?source=HMAC&number=2688",
          "https://csrc.nist.gov/projects/Cryptographic-Algorithm-Validation-Program/details?source=HMAC&number=2781"
        ]
      ],
      [
        "RSA",
        "Cert. #2289",
        [
          "https://csrc.nist.gov/projects/Cryptographic-Algorithm-Validation-Program/details?source=RSA&number=2289"
        ]
      ],
      [
        "SHS",
        "Certs. #3386 and #3480",
        [
          "https://csrc.nist.gov/projects/Cryptographic-Algorithm-Validation-Program/details?source=SHS&number=3386",
          "https://csrc.nist.gov/projects/Cryptographic-Algorithm-Validation-Program/details?source=SHS&number=3480"
        ]
      ]
    ],
    "Allowed Algorithms": "Diffie-Hellman (CVL Certs. #990 and #991, key agreement; key establishment methodology provides 112 bits of encryption strength); EC Diffie-Hellman (CVL Certs. #990, #991 and #992, key agreement; key establishment methodology provides 128 bits of encryption strength); EC Diffie-Hellman (CVL Certs. #923 and #924, key agreement; key establishment methodology provides 192 bits of encryption strength); HMAC-MD5; MD5; NDRNG; RSA (key wrapping; key establishment methodology provides 112 bits of encryption strength)",
    "Hardware Versions": "{BR-X64-001 (80-1009190-01) with FRUs (80-1009332-01, 80-1009341-01, 80-1009225-01, 80-1009227-01, 80-1009326-01, 80-1009441-01, 80-1009349-01, 80-1009348-01, 80-1009348-01), BR-X68-001 (80-1009230-01) with FRUs (80-1009332-01, 80-1009342-01, 80-1009225-01, 80-1009227-01, 80-1009326-01, 80-1009441-01, 80-1009349-01, 80-1009348-01, 80-1009348-01)} with FIPS Kit Brocade XBR-000195 (P/N: 80-1002006-02)",
    "Firmware Versions": "Fabric OS v8.1.0 (P/N 63-1001736-01)",
    "Product URL": "http://www.brocade.com/products/all/index.page"
  },
  "Vendor": {
    "Name": "Brocade Communications Systems, Inc.",
    "Website": "http://www.brocade.com",
    "Address": "130 Holger Way\nSan Jose, CA 95134\nUSA",
    "Contacts": [
      {
        "Name": "Hamid Sobouti",
        "Email": "hsobouti@brocade.com",
        "Phone": "408-333-4150",
        "Fax": "408-333-8101"
      }
    ]
  },
  "Related Files": [
    [
      "Security Policy",
      "https://csrc.nist.gov/CSRC/media/projects/cryptographic-module-validation-program/documents/security-policies/140sp3117.pdf"
    ],
    [
      "Consolidated Certificate",
      "https://csrc.nist.gov/CSRC/media/projects/cryptographic-module-validation-program/documents/certificates/FIPSConsolidatedCertFeb2018.pdf"
    ]
  ],
  "Validation History": [
    {
      "Date": "2/6/2018",
      "Type": "Initial",
      "Lab": "ÆGISOLVE"
    }
  ]
}

=== ratPoopert/csrc-scraper/tests/examples/cmvp/certificates/json/1479.json
{
  "$schema": "./cmvp-certificate.schema.json",
  "Certificate Number": "1479",
  "Details": {
    "Module Name": "Imation S200/D200",
    "Standard": "FIPS 140-2",
    "Status": "Historical",
    "Historical Reason": "RNG SP800-131A Revision 1 Transition",
    "Overall Level": 3,
    "Caveat": "Files distributed with the module mounted within the internal CD Drive are excluded from validation",
    "Module Type": "Hardware",
    "Embodiment": "Multi-chip standalone",
    "Description": "The IronKey Secure Flash Drives include a high-speed hardware-based 256 Bit AES cryptography engine for encrypting and decrypting NAND flash and RAM buffers via USB. It also includes RSA, HMAC, SHA-256, SHA-1, and RNG algorithms.",
    "Approved Algorithms": [
      [
        "AES",
        "Cert. #1034",
        [
          "https://csrc.nist.gov/projects/Cryptographic-Algorithm-Validation-Program/details?source=AES&number=1034"
        ]
      ],
      [
        "HMAC",
        "Cert. #579",
        [
          "https://csrc.nist.gov/projects/Cryptographic-Algorithm-Validation-Program/details?source=HMAC&number=579"
        ]
      ],
      [
        "RNG",
        "Certs. #587 and #702",
        [
          "https://csrc.nist.gov/projects/Cryptographic-Algorithm-Validation-Program/details?source=RNG&number=587",
          "https://csrc.nist.gov/projects/Cryptographic-Algorithm-Validation-Program/details?source=RNG&number=702"
        ]
      ],
      [
        "RSA",
        "Cert. #605",
        [
          "https://csrc.nist.gov/projects/Cryptographic-Algorithm-Validation-Program/details?source=RSA&number=605"
        ]
      ],
      [
        "SHS",
        "Certs. #987 and #1154",
        [
          "https://csrc.nist.gov/projects/Cryptographic-Algorithm-Validation-Program/details?source=SHS&number=987",
          "https://csrc.nist.gov/projects/Cryptographic-Algorithm-Validation-Program/details?source=SHS&number=1154"
        ]
      ]
    ],
    "Other Algorithms": "RSA (key wrapping; key establishment methodology provides 112 bits of encryption strength)",
    "Hardware Versions": "D2-S200-S01 (Rev 1), D2-S200-S02 (Rev 1), D2-S200-S04 (Rev 1), D2-S200-S08 (Rev 1), D2-S200-S16 (Rev 1), D2-D200-S01 (Rev 1), D2-D200-S02 (Rev 1), D2-D200-S04 (Rev 1), D2-D200-S08 (Rev 1), D2-D200-S16 (Rev 1) or D2-D200-S32 (Rev 1)",
    "Firmware Versions": "2.0.10, 2.0.11, 2.0.12, 2.0.13, 2.1.0, 2.1.1 or 2.1.2"
  },
  "Vendor": {
    "Name": "Imation Corp.",
    "Website": "http://www.imation.com/mobilesecurity",
    "Address": "Discovery Bldg. 1A-041\nOakdale, MN 55128\nUSA",
    "Contacts": [
      {
        "Name": "Larry Hamid",
        "Email": "crypto-ims@imation.com",
        "Phone": "408-737-4308"
      }
    ]
  },
  "Related Files": [
    [
      "Security Policy",
      "https://csrc.nist.gov/CSRC/media/projects/cryptographic-module-validation-program/documents/security-policies/140sp1479.pdf"
    ],
    [
      "Consolidated Certificate",
      "https://csrc.nist.gov/CSRC/media/projects/cryptographic-module-validation-program/documents/certificates/FIPS140ConsolidatedCertList0002.pdf"
    ]
  ],
  "Validation History": [
    {
      "Date": "1/7/2011",
      "Type": "Initial",
      "Lab": "UL VERIFICATION SERVICES INC"
    },
    {
      "Date": "8/9/2011",
      "Type": "Update",
      "Lab": "UL VERIFICATION SERVICES INC"
    },
    {
      "Date": "9/19/2011",
      "Type": "Update",
      "Lab": "UL VERIFICATION SERVICES INC"
    },
    {
      "Date": "10/4/2011",
      "Type": "Update",
      "Lab": "UL VERIFICATION SERVICES INC"
    },
    {
      "Date": "10/26/2011",
      "Type": "Update",
      "Lab": "UL VERIFICATION SERVICES INC"
    },
    {
      "Date": "4/24/2012",
      "Type": "Update",
      "Lab": "UL VERIFICATION SERVICES INC"
    }
  ]
}

=== ratPoopert/csrc-scraper/tests/cmvp/json/2543.json
{
  "$schema": "./cmvp-certificate.schema.json",
  "Certificate Number": "2543",
  "Details": {
    "Module Name": "FortiClient 5.0 VPN Client",
    "Standard": "FIPS 140-2",
    "Status": "Historical",
    "Historical Reason": "Moved to historical list due to sunsetting",
    "Overall Level": 2,
    "Caveat": "When operated in FIPS mode and configured according to the Entropy Token Section of the Security Policy. The module generates cryptographic keys whose strengths are modified by available entropy. There is no assurance of the minimum strength of generated keys",
    "Security Level Exceptions": [
      "Physical Security: N/A",
      "Mitigation of Other Attacks: N/A"
    ],
    "Module Type": "Software",
    "Embodiment": "Multi-Chip Stand Alone",
    "Description": "The FortiClient VPN client provides a FIPS 140-2 validated, IPSec and SSL VPN client for Windows platforms.",
    "Tested Configuration(s)": [
      "Windows 7 Enterprise Edition running on a Dell Optiplex 755 with the Fortinet entropy token (part number FTR-ENT-1) (single-user mode)"
    ],
    "Approved Algorithms": [
      [
        "AES",
        "Certs. #2912 and #2924",
        [
          "https://csrc.nist.gov/projects/Cryptographic-Algorithm-Validation-Program/details?source=AES&number=2912",
          "https://csrc.nist.gov/projects/Cryptographic-Algorithm-Validation-Program/details?source=AES&number=2924"
        ]
      ],
      [
        "CVL",
        "Cert. #329",
        [
          "https://csrc.nist.gov/projects/Cryptographic-Algorithm-Validation-Program/details?source=Component&number=329"
        ]
      ],
      [
        "DRBG",
        "Cert. #538",
        [
          "https://csrc.nist.gov/projects/Cryptographic-Algorithm-Validation-Program/details?source=DRBG&number=538"
        ]
      ],
      [
        "HMAC",
        "Certs. #1842 and #1851",
        [
          "https://csrc.nist.gov/projects/Cryptographic-Algorithm-Validation-Program/details?source=HMAC&number=1842",
          "https://csrc.nist.gov/projects/Cryptographic-Algorithm-Validation-Program/details?source=HMAC&number=1851"
        ]
      ],
      [
        "PBKDF",
        "vendor affirmed"
      ],
      [
        "RSA",
        "Cert. #1533",
        [
          "https://csrc.nist.gov/projects/Cryptographic-Algorithm-Validation-Program/details?source=RSA&number=1533"
        ]
      ],
      [
        "SHS",
        "Certs. #2451 and #2460",
        [
          "https://csrc.nist.gov/projects/Cryptographic-Algorithm-Validation-Program/details?source=SHS&number=2451",
          "https://csrc.nist.gov/projects/Cryptographic-Algorithm-Validation-Program/details?source=SHS&number=2460"
        ]
      ],
      [
        "Triple-DES",
        "Certs. #1728 and #1737",
        [
          "https://csrc.nist.gov/projects/Cryptographic-Algorithm-Validation-Program/details?source=TDES&number=1728",
          "https://csrc.nist.gov/projects/Cryptographic-Algorithm-Validation-Program/details?source=TDES&number=1737"
        ]
      ]
    ]
  },
  "Vendor": {
    "Name": "Fortinet, Inc.",
    "Website": "http://www.fortinet.com/",
    "Address": "326 Moodie Drive\nOttawa, ON K2H 8G3\nCanada",
    "Contacts": [
      {
        "Name": "Alan Kaye",
        "Email": "akaye@fortinet.com",
        "Phone": "613-225-9381",
        "Fax": "613-225-2951"
      }
    ]
  },
  "Related Files": [
    [
      "Security Policy",
      "https://csrc.nist.gov/CSRC/media/projects/cryptographic-module-validation-program/documents/security-policies/140sp2543.pdf"
    ],
    [
      "Consolidated Certificate",
      "https://csrc.nist.gov/CSRC/media/projects/cryptographic-module-validation-program/documents/certificates/FIPS140ConsolidatedCertJan2016.pdf"
    ]
  ],
  "Validation History": [
    {
      "Date": "1/26/2016",
      "Type": "Initial",
      "Lab": "DXC Technology"
    }
  ]
}

=== ratPoopert/csrc-scraper/tests/cmvp/json/3843.json
{
  "$schema": "./cmvp-certificate.schema.json",
  "Certificate Number": "3843",
  "Details": {
    "Module Name": "Cisco Adaptive Security Appliance (ASA) Virtual",
    "Standard": "FIPS 140-2",
    "Status": "Historical",
    "Historical Reason": "SP 800-56Arev3 transition",
    "Overall Level": 1,
    "Caveat": "When operated in FIPS mode",
    "Security Level Exceptions": [
      "Roles, Services, and Authentication: Level 3",
      "Physical Security: N/A",
      "Mitigation of Other Attacks: N/A"
    ],
    "Module Type": "Software",
    "Embodiment": "Multi-Chip Stand Alone",
    "Description": "The market-leading Cisco ASA Security Appliance Series deliver robust user and application policy enforcement, multi-vector attack protection, and secure connectivity services in cost-effective, easy-to-deploy solutions. The ASA Virtual Adaptive Security Appliances provide comprehensive security, performance, and reliability for network environments of all sizes.",
    "Tested Configuration(s)": [
      "FXOS version 2 on NFVIS 3 running on ENCS 5412 with Intel Xeon D-1528 (single-user mode)",
      "FXOS version 2 on VMware ESXi 6.0 running on Cisco UCS C220 M5 with Intel Xeon Silver 4110",
      "FXOS version 2 on VMware ESXi 6.5 running on Cisco UCS C220 M5 with Intel Xeon Silver 4110"
    ],
    "Approved Algorithms": [
      [
        "AES",
        "Cert. #5008",
        [
          "https://csrc.nist.gov/projects/Cryptographic-Algorithm-Validation-Program/details?source=AES&number=5008"
        ]
      ],
      [
        "CVL",
        "Cert. #1561",
        [
          "https://csrc.nist.gov/projects/Cryptographic-Algorithm-Validation-Program/details?source=Component&number=1561"
        ]
      ],
      [
        "DRBG",
        "Cert. #1828",
        [
          "https://csrc.nist.gov/projects/Cryptographic-Algorithm-Validation-Program/details?source=DRBG&number=1828"
        ]
      ],
      [
        "ECDSA",
        "Cert. #1277",
        [
          "https://csrc.nist.gov/projects/Cryptographic-Algorithm-Validation-Program/details?source=ECDSA&number=1277"
        ]
      ],
      [
        "HMAC",
        "Cert. #3329",
        [
          "https://csrc.nist.gov/projects/Cryptographic-Algorithm-Validation-Program/details?source=HMAC&number=3329"
        ]
      ],
      [
        "RSA",
        "Cert. #2703",
        [
          "https://csrc.nist.gov/projects/Cryptographic-Algorithm-Validation-Program/details?source=RSA&number=2703"
        ]
      ],
      [
        "SHS",
        "Cert. #4074",
        [
          "https://csrc.nist.gov/projects/Cryptographic-Algorithm-Validation-Program/details?source=SHS&number=4074"
        ]
      ],
      [
        "Triple-DES",
        "Cert. #2584",
        [
          "https://csrc.nist.gov/projects/Cryptographic-Algorithm-Validation-Program/details?source=TDES&number=2584"
        ]
      ]
    ],
    "Allowed Algorithms": "Diffie-Hellman (CVL Cert. #1561, key agreement; key establishment methodology provides between 112 and 150 bits of encryption strength); NDRNG; RSA (key wrapping; key establishment methodology provides 112 bits of encryption strength)",
    "Software Versions": "9.12"
  },
  "Vendor": {
    "Name": "Cisco Systems, Inc.",
    "Website": "http://www.cisco.com/",
    "Address": "170 West Tasman Drive\nSan Jose, CA 95134\nUSA",
    "Contacts": [
      {
        "Name": "Global Certification Team",
        "Email": "certteam@cisco.com"
      }
    ]
  },
  "Related Files": [
    [
      "Security Policy",
      "https://csrc.nist.gov/CSRC/media/projects/cryptographic-module-validation-program/documents/security-policies/140sp3843.pdf"
    ],
    [
      "Consolidated Certificate",
      "https://csrc.nist.gov/CSRC/media/projects/cryptographic-module-validation-program/documents/certificates/March%202021_010421_0724_signed.pdf"
    ]
  ],
  "Validation History": [
    {
      "Date": "3/10/2021",
      "Type": "Initial",
      "Lab": "GOSSAMER SECURITY SOLUTIONS INC"
    }
  ]
}

=== ratPoopert/csrc-scraper/tests/examples/cmvp/certificates/json/2038.json
{
  "$schema": "./cmvp-certificate.schema.json",
  "Certificate Number": "2038",
  "Details": {
    "Module Name": "CryptoComply for Server",
    "Standard": "FIPS 140-2",
    "Status": "Active",
    "Sunset Date": "3/8/2026",
    "Overall Level": 1,
    "Caveat": "When operated in FIPS mode. The module makes no assurance of the minimum strength of random strings and generated keys.",
    "Module Type": "Software",
    "Embodiment": "Multi-chip standalone",
    "Description": "SafeLogic's CryptoComply for Server is designed to provide FIPS 140-2 validated cryptographic functionality and is available for licensing.",
    "Tested Configuration(s)": [
      "CentOS 7 running on a Dell PowerEdge R830 with an Intel Xeon E5-4667v4 with PAA",
      "CentOS 7 running on a Dell PowerEdge R830 with an Intel Xeon E5-4667v4 without PAA",
      "macOS 13 (Ventura) running on a Mac Mini M2 with an Apple M2",
      "Windows Server 2022 running on a Dell PowerEdge R830 with an Intel Xeon E5-4667v4 with PAA",
      "Windows Server 2022 running on a Dell PowerEdge R830 with an Intel Xeon E5-4667v4 without PAA (single-user mode)"
    ],
    "Approved Algorithms": [
      [
        "AES",
        "Cert. #A4873",
        [
          "https://csrc.nist.gov/projects/Cryptographic-Algorithm-Validation-Program/details?source=A&number=4873"
        ]
      ],
      [
        "CKG",
        "vendor affirmed",
        []
      ],
      [
        "DRBG",
        "Cert. #A4873",
        [
          "https://csrc.nist.gov/projects/Cryptographic-Algorithm-Validation-Program/details?source=A&number=4873"
        ]
      ],
      [
        "DSA",
        "Cert. #A4873",
        [
          "https://csrc.nist.gov/projects/Cryptographic-Algorithm-Validation-Program/details?source=A&number=4873"
        ]
      ],
      [
        "ECDSA",
        "Cert. #A4873",
        [
          "https://csrc.nist.gov/projects/Cryptographic-Algorithm-Validation-Program/details?source=A&number=4873"
        ]
      ],
      [
        "HMAC",
        "Cert. #A4873",
        [
          "https://csrc.nist.gov/projects/Cryptographic-Algorithm-Validation-Program/details?source=A&number=4873"
        ]
      ],
      [
        "RSA",
        "Cert. #A4873",
        [
          "https://csrc.nist.gov/projects/Cryptographic-Algorithm-Validation-Program/details?source=A&number=4873"
        ]
      ],
      [
        "SHS",
        "Cert. #A4873",
        [
          "https://csrc.nist.gov/projects/Cryptographic-Algorithm-Validation-Program/details?source=A&number=4873"
        ]
      ],
      [
        "Triple-DES",
        "Cert. #A4873",
        [
          "https://csrc.nist.gov/projects/Cryptographic-Algorithm-Validation-Program/details?source=A&number=4873"
        ]
      ]
    ],
    "Other Algorithms": "N/A",
    "Software Versions": "2.1.2",
    "Product URL": "https://www.safelogic.com/cryptocomply"
  },
  "Vendor": {
    "Name": "SafeLogic Inc.",
    "Website": "http://www.safelogic.com",
    "Address": "530 Lytton Ave\nSuite 200\nPalo Alto, CA 94301\nUSA",
    "Contacts": [
      {
        "Name": "SafeLogic Inside Sales",
        "Email": "sales@safelogic.com",
        "Phone": "844-436-2797"
      }
    ]
  },
  "Related Files": [
    [
      "Security Policy",
      "https://csrc.nist.gov/CSRC/media/projects/cryptographic-module-validation-program/documents/security-policies/140sp2038.pdf"
    ],
    [
      "Consolidated Certificate",
      "https://csrc.nist.gov/CSRC/media/projects/cryptographic-module-validation-program/documents/certificates/FIPS140ConsolidatedCertList0035.pdf"
    ]
  ],
  "Validation History": [
    {
      "Date": "11/15/2013",
      "Type": "Initial",
      "Lab": "EWA CANADA"
    },
    {
      "Date": "1/23/2014",
      "Type": "Update",
      "Lab": "EWA CANADA"
    },
    {
      "Date": "2/20/2014",
      "Type": "Update",
      "Lab": "EWA CANADA"
    },
    {
      "Date": "1/25/2016",
      "Type": "Update",
      "Lab": ""
    },
    {
      "Date": "2/5/2016",
      "Type": "Update",
      "Lab": "ACUMEN SECURITY, LLC"
    },
    {
      "Date": "3/29/2018",
      "Type": "Update",
      "Lab": "ACUMEN SECURITY, LLC"
    },
    {
      "Date": "7/24/2020",
      "Type": "Update",
      "Lab": "ÆGISOLVE"
    },
    {
      "Date": "3/9/2021",
      "Type": "Update",
      "Lab": "EWA CANADA"
    },
    {
      "Date": "5/25/2021",
      "Type": "Update",
      "Lab": "ÆGISOLVE"
    },
    {
      "Date": "1/17/2023",
      "Type": "Update",
      "Lab": "EWA CANADA"
    },
    {
      "Date": "4/16/2024",
      "Type": "Update",
      "Lab": "EWA CANADA"
    }
  ]
}
