=== ratPoopert/csrc-scraper/tests/examples/cmvp/certificates/json/cmvp-certificate.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "CMVP Certificate",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "$schema": {
      "type": "string"
    },
    "Certificate Number": {
      "type": "string",
      "pattern": "^[0-9]+$"
    },
    "Details": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "Allowed Algorithms": {
          "type": "string"
        },
        "Entropy": {
          "type": "string"
        },
        "Module Name": {
          "type": "string"
        },
        "Standard": {
          "type": "string",
          "enum": [
            "FIPS 140-1",
            "FIPS 140-2",
            "FIPS 140-3"
          ]
        },
        "Status": {
          "type": "string",
          "enum": [
            "Active",
            "Historical",
            "Revoked"
          ]
        },
        "Sunset Date": {
          "type": "string"
        },
        "Historical Reason": {
          "type": "string"
        },
        "Overall Level": {
          "type": "integer",
          "enum": [
            1,
            2,
            3,
            4
          ]
        },
        "Caveat": {
          "type": "string"
        },
        "Security Level Exceptions": {
          "type": "array",
          "minItems": 1,
          "additionalItems": false,
          "items": {
            "type": "string"
          }
        },
        "Module Type": {
          "type": "string",
          "enum": [
            "Software",
            "Hardware"
          ]
        },
        "Embodiment": {
          "type": "string",
          "enum": [
            "Multi-chip embedded",
            "Multi-Chip Embedded",
            "Multi-chip standalone",
            "Single-chip",
            "Single Chip",
            "Multi-Chip Stand Alone"
          ]
        },
        "Description": {
          "type": "string"
        },
        "Tested Configuration(s)": {
          "type": "array",
          "minItems": 1,
          "additionalItems": false,
          "items": {
            "type": "string"
          }
        },
        "Approved Algorithms": {
          "type": "array",
          "minItems": 1,
          "additionalItems": false,
          "items": {
            "type": "array",
            "additionalItems": false,
            "items": [
              {
                "type": "string"
              },
              {
                "type": "string"
              },
              {
                "type": "array",
                "items": {
                  "type": "string",
                  "format": "uri"
                }
              }
            ]
          }
        },
        "Other Algorithms": {
          "type": "string"
        },
        "Software Versions": {
          "type": "string"
        },
        "Hardware Versions": {
          "type": "string"
        },
        "Firmware Versions": {
          "type": "string"
        },
        "Product URL": {
          "type": "string",
          "format": "uri"
        }
      },
      "required": [
        "Module Name",
        "Standard",
        "Status",
        "Overall Level",
        "Module Type",
        "Embodiment",
        "Description"
      ]
    },
    "Vendor": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "Name": {
          "type": "string"
        },
        "Website": {
          "type": "string",
          "format": "uri"
        },
        "Address": {
          "type": "string"
        },
        "Contacts": {
          "type": "array",
          "minLength": 1,
          "maxLength": 2,
          "items": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
              "Name": {
                "type": "string"
              },
              "Email": {
                "type": "string",
                "format": "email"
              },
              "Phone": {
                "type": "string"
              },
              "Fax": {
                "type": "string"
              }
            },
            "required": [
              "Name",
              "Email"
            ]
          }
        }
      },
      "required": [
        "Name",
        "Website",
        "Address",
        "Contacts"
      ]
    },
    "Related Files": {
      "type": "array",
      "additionalItems": false,
      "items": {
        "type": "array",
        "additionalItems": false,
        "items": [
          {
            "type": "string"
          },
          {
            "type": "string",
            "format": "uri"
          }
        ]
      }
    },
    "Validation History": {
      "type": "array",
      "minItems": 1,
      "additionalItems": false,
      "items": {
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "Date": {
            "type": "string"
          },
          "Type": {
            "type": "string",
            "enum": [
              "Initial",
              "Update"
            ]
          },
          "Lab": {
            "type": "string"
          }
        },
        "required": [
          "Date",
          "Type",
          "Lab"
        ]
      }
    }
  },
  "required": [
    "Certificate Number",
    "Details",
    "Vendor",
    "Related Files",
    "Validation History"
  ]
}

=== ratPoopert/csrc-scraper/tests/examples/cmvp/certificates/json/548.json
{
    "$schema": "./cmvp-certificate.schema.json",
    "Certificate Number": "548",
    "Details": {
        "Module Name": "ID-One Cosmo 64 v5",
        "Standard": "FIPS 140-2",
        "Status": "Historical",
        "Historical Reason": "RNG SP800-131A Revision 1 Transition",
        "Overall Level": 3,
        "Caveat": "None",
        "Module Type": "Hardware",
        "Embodiment": "Single-chip",
        "Description": "The ID-One Cosmo 64 v5 is a JavaCard cryptographic module with dual interface (ISO 7816 & ISO 14443) specifically designed for identity and government market needs. It offers a full 64K Byte of EEPROM space available for customer discretionary use, together with on card cryptographic services such as TDES, AES, Elliptic Curve and 2048-bit RSA algorithms with on-card key generation. It is compliant to Java Card v2.2 and Open Platform v2.1.1A. To protect against skimming, a built-in firewall allows application developers to disable contactless access for sensitive operations. Additional features include On- Card fingerprint matching and Logical Channels. The ID-One Cosmo 64 v5 is available in contact only, dual interface, or contactless only formats.",
        "Approved Algorithms": [
            [
                "RNG",
                "Cert. #94",
                [
                    "https://csrc.nist.gov/projects/Cryptographic-Algorithm-Validation-Program/details?source=RNG&number=94"
                ]
            ],
            [
                "RSA",
                "Cert. #43",
                [
                    "https://csrc.nist.gov/projects/Cryptographic-Algorithm-Validation-Program/details?source=RSA&number=43"
                ]
            ],
            [
                "SHS",
                "Cert. #209",
                [
                    "https://csrc.nist.gov/projects/Cryptographic-Algorithm-Validation-Program/details?source=SHS&number=209"
                ]
            ],
            [
                "Triple-DES",
                "Cert. #232",
                [
                    "https://csrc.nist.gov/projects/Cryptographic-Algorithm-Validation-Program/details?source=TDES&number=232"
                ]
            ],
            [
                "Triple-DES MAC",
                "Triple-DES Cert. #232, vendor affirmed",
                []
            ]
        ],
        "Other Algorithms": "DES (Cert. #246); DES MAC (Cert. #246, vendor affirmed)",
        "Hardware Versions": "P/N 77",
        "Firmware Versions": "E303-063683 and E303-063684"
    },
    "Vendor": {
        "Name": "Oberthur Card Systems",
        "Website": "http://www.oberthurusa.com",
        "Address": "4250 Pleasant Valley Road\nChantilly, VA 20151\nUSA",
        "Contacts": [
            {
                "Name": "Christophe Goyet",
                "Email": "Christophe.Goyet@oberthurusa.com",
                "Phone": "703-263-0100",
                "Fax": "703-263-7134"
            }
        ]
    },
    "Related Files": [
        [
            "Security Policy",
            "https://csrc.nist.gov/CSRC/media/projects/cryptographic-module-validation-program/documents/security-policies/140sp548.pdf"
        ],
        [
            "Certificate",
            "https://csrc.nist.gov/CSRC/media/projects/cryptographic-module-validation-program/documents/certificates/140crt548.pdf"
        ]
    ],
    "Validation History": [
        {
            "Date": "6/9/2005",
            "Type": "Initial",
            "Lab": "UL VERIFICATION SERVICES INC"
        },
        {
            "Date": "9/23/2005",
            "Type": "Update",
            "Lab": ""
        },
        {
            "Date": "5/16/2006",
            "Type": "Update",
            "Lab": ""
        },
        {
            "Date": "8/16/2006",
            "Type": "Update",
            "Lab": ""
        },
        {
            "Date": "4/30/2007",
            "Type": "Update",
            "Lab": ""
        },
        {
            "Date": "10/15/2007",
            "Type": "Update",
            "Lab": ""
        }
    ]
}

=== ratPoopert/csrc-scraper/tests/examples/cmvp/certificates/json/160.json
{
  "$schema": "./cmvp-certificate.schema.json",
  "Certificate Number": "160",
  "Details": {
    "Module Name": "CSA8000 Cryptographic Adapter",
    "Standard": "FIPS 140-1",
    "Status": "Historical",
    "Historical Reason": "Validation Sunsetting Policy - FIPS 140-1 Certificate",
    "Overall Level": 3,
    "Caveat": "When operated in FIPS mode",
    "Module Type": "Hardware",
    "Embodiment": "Multi-chip embedded",
    "Description": "The Eracom CSA8000 Cryptographic Adapter is an intelligent PCI adapter card that provides a wide range of cryptographic functions with dedicated DES/3DES and RSA hardware accelerators. The module implements the PKCS#11 cryptographic API and provides a comprehensive compliance to the PKCS#11 standard as well as vendor specific extensions.",
    "Approved Algorithms": [
      [
        "DSA",
        "Cert. #47",
        [
          "https://csrc.nist.gov/projects/Cryptographic-Algorithm-Validation-Program/details?source=DSA&number=47"
        ]
      ],
      [
        "RSA",
        "PKCS #1 for Signatures; vendor affirmed",
        []
      ],
      [
        "SHA-1",
        "Cert. #55",
        [
          "https://csrc.nist.gov/projects/Cryptographic-Algorithm-Validation-Program/details?source=SHS&number=55"
        ]
      ],
      [
        "Triple-DES",
        "Cert. #63",
        [
          "https://csrc.nist.gov/projects/Cryptographic-Algorithm-Validation-Program/details?source=TDES&number=63"
        ]
      ]
    ],
    "Other Algorithms": "DES (Cert. #124); HMAC-SHA-1; RSA; CAST128; IDEA; AES (Rijndael); RC2; RC4; MD2; MD5; Diffie-Hellman (key agreement)",
    "Hardware Versions": "Revision G, Cprov",
    "Firmware Versions": "1.10",
    "Product URL": "http://www.eracom-tech.com/protectserver_orange.0.html"
  },
  "Vendor": {
    "Name": "Eracom Technologies Group, Eracom Technologies Australia, Pty. Ltd.",
    "Website": "http://www.eracom-tech.com",
    "Address": "28 Greg Chappell Drive\nBurleigh Heads, QLD 4220\nAustralia",
    "Contacts": [
      {
        "Name": "Gerry Scott",
        "Email": "sales@eracom-tech.com",
        "Phone": "916-677-2450",
        "Fax": "916-677-2460"
      }
    ]
  },
  "Related Files": [
    [
      "Security Policy",
      "https://csrc.nist.gov/CSRC/media/projects/cryptographic-module-validation-program/documents/security-policies/140sp160.pdf"
    ],
    [
      "Certificate",
      "https://csrc.nist.gov/CSRC/media/projects/cryptographic-module-validation-program/documents/certificates/140crt160.pdf"
    ]
  ],
  "Validation History": [
    {
      "Date": "7/27/2001",
      "Type": "Initial",
      "Lab": "CYGNACOM SOLUTIONS INC"
    },
    {
      "Date": "10/18/2005",
      "Type": "Update",
      "Lab": ""
    }
  ]
}

=== ratPoopert/csrc-scraper/tests/examples/cmvp/certificates/json/2921.json
{
  "$schema": "./cmvp-certificate.schema.json",
  "Certificate Number": "2921",
  "Details": {
    "Module Name": "Juniper Networks SRX1400, SRX3400, and SRX3600 Services Gateways",
    "Standard": "FIPS 140-2",
    "Status": "Historical",
    "Historical Reason": "Moved to historical list due to sunsetting",
    "Overall Level": 2,
    "Caveat": "When operated in FIPS mode and with the tamper-evident seals installed as indicated in the Security Policy",
    "Security Level Exceptions": [
      "Roles, Services, and Authentication: Level 3",
      "Design Assurance: Level 3",
      "Mitigation of Other Attacks: N/A"
    ],
    "Module Type": "Hardware",
    "Embodiment": "Multi-Chip Stand Alone",
    "Description": "Juniper Networks SRX Series Services Gateways provide the essential capabilities necessary to connect, secure, and manage enterprise and service provider networks, from the smallest sites to the largest headquarters and data centers.",
    "Tested Configuration(s)": [
      "N/A"
    ],
    "Approved Algorithms": [
      [
        "AES",
        "Certs. #4054, #4056 and #4329",
        [
          "https://csrc.nist.gov/projects/Cryptographic-Algorithm-Validation-Program/details?source=AES&number=4054",
          "https://csrc.nist.gov/projects/Cryptographic-Algorithm-Validation-Program/details?source=AES&number=4056",
          "https://csrc.nist.gov/projects/Cryptographic-Algorithm-Validation-Program/details?source=AES&number=4329"
        ]
      ],
      [
        "CVL",
        "Certs. #880 and #926",
        [
          "https://csrc.nist.gov/projects/Cryptographic-Algorithm-Validation-Program/details?source=Component&number=880",
          "https://csrc.nist.gov/projects/Cryptographic-Algorithm-Validation-Program/details?source=Component&number=926"
        ]
      ],
      [
        "DRBG",
        "Certs. #1216 and #1399",
        [
          "https://csrc.nist.gov/projects/Cryptographic-Algorithm-Validation-Program/details?source=DRBG&number=1216",
          "https://csrc.nist.gov/projects/Cryptographic-Algorithm-Validation-Program/details?source=DRBG&number=1399"
        ]
      ],
      [
        "DSA",
        "Certs. #1096 and #1104",
        [
          "https://csrc.nist.gov/projects/Cryptographic-Algorithm-Validation-Program/details?source=DSA&number=1096",
          "https://csrc.nist.gov/projects/Cryptographic-Algorithm-Validation-Program/details?source=DSA&number=1104"
        ]
      ],
      [
        "ECDSA",
        "Certs. #909 and #917",
        [
          "https://csrc.nist.gov/projects/Cryptographic-Algorithm-Validation-Program/details?source=ECDSA&number=909",
          "https://csrc.nist.gov/projects/Cryptographic-Algorithm-Validation-Program/details?source=ECDSA&number=917"
        ]
      ],
      [
        "HMAC",
        "Certs. #2646, #2648 and #2867",
        [
          "https://csrc.nist.gov/projects/Cryptographic-Algorithm-Validation-Program/details?source=HMAC&number=2646",
          "https://csrc.nist.gov/projects/Cryptographic-Algorithm-Validation-Program/details?source=HMAC&number=2648",
          "https://csrc.nist.gov/projects/Cryptographic-Algorithm-Validation-Program/details?source=HMAC&number=2867"
        ]
      ],
      [
        "KTS",
        "AES Cert. #4054 and HMAC Cert. #2646",
        []
      ],
      [
        "KTS",
        "AES Cert. #4056 and HMAC Cert. #2648",
        []
      ],
      [
        "KTS",
        "Triple-DES Cert. #2223 and HMAC Cert. #2648",
        []
      ],
      [
        "KTS",
        "Triple-DES Cert. #2224 and HMAC Cert. #2646",
        []
      ],
      [
        "RSA",
        "Certs. #2087 and #2202",
        [
          "https://csrc.nist.gov/projects/Cryptographic-Algorithm-Validation-Program/details?source=RSA&number=2087",
          "https://csrc.nist.gov/projects/Cryptographic-Algorithm-Validation-Program/details?source=RSA&number=2202"
        ]
      ],
      [
        "SHS",
        "Certs. #3341, #3343 and #3571",
        [
          "https://csrc.nist.gov/projects/Cryptographic-Algorithm-Validation-Program/details?source=SHS&number=3341",
          "https://csrc.nist.gov/projects/Cryptographic-Algorithm-Validation-Program/details?source=SHS&number=3343",
          "https://csrc.nist.gov/projects/Cryptographic-Algorithm-Validation-Program/details?source=SHS&number=3571"
        ]
      ],
      [
        "Triple-DES",
        "Certs. #2222, #2223 and #2224",
        [
          "https://csrc.nist.gov/projects/Cryptographic-Algorithm-Validation-Program/details?source=TDES&number=2222",
          "https://csrc.nist.gov/projects/Cryptographic-Algorithm-Validation-Program/details?source=TDES&number=2223",
          "https://csrc.nist.gov/projects/Cryptographic-Algorithm-Validation-Program/details?source=TDES&number=2224"
        ]
      ]
    ],
    "Other Algorithms": "Diffie-Hellman (key agreement; key establishment methodology provides between 112 and 192 bits of encryption strength); EC Diffie-Hellman (key agreement; key establishment methodology provides 128 or 192 bits of encryption strength); NDRNG; ARCFOUR; Blowfish; CAST; HMAC-MD5; HMAC-RIPEMD160; UMAC",
    "Hardware Versions": "P/Ns SRX1400BASE-GE-AC with [1] or [2], SRX1400BASE-GE-DC with [1] or [2], SRX3400BASE-AC with [2], SRX3400BASE-DC with [2], SRX3400BASE-DC2 with [2], SRX3600BASE-AC with [2], SRX3600BASE-DC with [2], and SRX3600BASE-DC2 with [2]; Service Processing Cards SRX1K-NPC-SPC-1-10-40 [1] or SRX3K-SPC-1-10-40 [2]; with Tamper Seals JNPR-FIPS-TAMPER-LBLS",
    "Firmware Versions": "JUNOS-FIPS 12.3X48-D30"
  },
  "Vendor": {
    "Name": "Juniper Networks, Inc.",
    "Website": "http://www.juniper.net",
    "Address": "1133 Innovation Way\nSunnyvale, CA 94089\nUSA",
    "Contacts": [
      {
        "Name": "Jaz Lin",
        "Email": "jazlin@juniper.net",
        "Phone": "408-745-2000"
      },
      {
        "Name": "Vann (Vanna) Nguyen",
        "Email": "vann@juniper.net",
        "Phone": "408-745-2000"
      }
    ]
  },
  "Related Files": [
    [
      "Security Policy",
      "https://csrc.nist.gov/CSRC/media/projects/cryptographic-module-validation-program/documents/security-policies/140sp2921.pdf"
    ],
    [
      "Consolidated Certificate",
      "https://csrc.nist.gov/CSRC/media/projects/cryptographic-module-validation-program/documents/certificates/FIPS140ConsolidatedCertJune2017.pdf"
    ]
  ],
  "Validation History": [
    {
      "Date": "6/14/2017",
      "Type": "Initial",
      "Lab": "UL VERIFICATION SERVICES INC"
    }
  ]
}

=== ratPoopert/csrc-scraper/tests/cmvp/json/4065.json
{
  "$schema": "./cmvp-certificate.schema.json",
  "Certificate Number": "4065",
  "Details": {
    "Module Name": "Thales Alenia Space cryptographic module for Microsemi RTAX FPGA",
    "Standard": "FIPS 140-2",
    "Status": "Active",
    "Sunset Date": "9/21/2026",
    "Overall Level": 1,
    "Caveat": "When installed, initialized and configured as specified in Section 12.4 of the Security Policy.",
    "Security Level Exceptions": [
      "Mitigation of Other Attacks: N/A"
    ],
    "Module Type": "Hardware",
    "Embodiment": "Multi-Chip Embedded",
    "Description": "Cryptographic module encrypt and decrypt input packets, using one of the thirty two possible keys. There are several TC/TM to check: status, number of packets correctly deciphered, number of ciphered packet, etc. There are three UART interfaces for: ground, key and housekeeping (the last one has a redundant interface).",
    "Tested Configuration(s)": [
      "N/A"
    ],
    "Approved Algorithms": [
      [
        "AES",
        "Cert. #A1721",
        [
          "https://csrc.nist.gov/projects/Cryptographic-Algorithm-Validation-Program/details?source=A&number=1721"
        ]
      ]
    ],
    "Allowed Algorithms": "N/A",
    "Hardware Versions": "RTAX2000S FPGA; 28C010T EEPROM",
    "Firmware Versions": "3.32.00; 3.32.04"
  },
  "Vendor": {
    "Name": "Thales Alenia Space",
    "Website": "http://www.thalesgroup.com/es/espana/espacio",
    "Address": "Calle Einstein, 7\nTres Cantos, Madrid 28760\nSpain",
    "Contacts": [
      {
        "Name": "Irene Potti Huerta",
        "Email": "irene.potti@thalesaleniaspace.com",
        "Phone": "+34 91 807 79 00"
      }
    ]
  },
  "Related Files": [
    [
      "Security Policy",
      "https://csrc.nist.gov/CSRC/media/projects/cryptographic-module-validation-program/documents/security-policies/140sp4065.pdf"
    ],
    [
      "Consolidated Certificate",
      "https://csrc.nist.gov/CSRC/media/projects/cryptographic-module-validation-program/documents/certificates/November%202021_011221_0923_signed.pdf"
    ]
  ],
  "Validation History": [
    {
      "Date": "11/2/2021",
      "Type": "Initial",
      "Lab": "DEKRA Testing and Certification S.A.U"
    }
  ]
}
