=== ratPoopert/csrc-scraper/tests/examples/cmvp/certificates/json/cmvp-certificate.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "CMVP Certificate",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "$schema": {
      "type": "string"
    },
    "Certificate Number": {
      "type": "string",
      "pattern": "^[0-9]+$"
    },
    "Details": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "Allowed Algorithms": {
          "type": "string"
        },
        "Entropy": {
          "type": "string"
        },
        "Module Name": {
          "type": "string"
        },
        "Standard": {
          "type": "string",
          "enum": [
            "FIPS 140-1",
            "FIPS 140-2",
            "FIPS 140-3"
          ]
        },
        "Status": {
          "type": "string",
          "enum": [
            "Active",
            "Historical",
            "Revoked"
          ]
        },
        "Sunset Date": {
          "type": "string"
        },
        "Historical Reason": {
          "type": "string"
        },
        "Overall Level": {
          "type": "integer",
          "enum": [
            1,
            2,
            3,
            4
          ]
        },
        "Caveat": {
          "type": "string"
        },
        "Security Level Exceptions": {
          "type": "array",
          "minItems": 1,
          "additionalItems": false,
          "items": {
            "type": "string"
          }
        },
        "Module Type": {
          "type": "string",
          "enum": [
            "Software",
            "Hardware"
          ]
        },
        "Embodiment": {
          "type": "string",
          "enum": [
            "Multi-chip embedded",
            "Multi-Chip Embedded",
            "Multi-chip standalone",
            "Single-chip",
            "Single Chip",
            "Multi-Chip Stand Alone"
          ]
        },
        "Description": {
          "type": "string"
        },
        "Tested Configuration(s)": {
          "type": "array",
          "minItems": 1,
          "additionalItems": false,
          "items": {
            "type": "string"
          }
        },
        "Approved Algorithms": {
          "type": "array",
          "minItems": 1,
          "additionalItems": false,
          "items": {
            "type": "array",
            "additionalItems": false,
            "items": [
              {
                "type": "string"
              },
              {
                "type": "string"
              },
              {
                "type": "array",
                "items": {
                  "type": "string",
                  "format": "uri"
                }
              }
            ]
          }
        },
        "Other Algorithms": {
          "type": "string"
        },
        "Software Versions": {
          "type": "string"
        },
        "Hardware Versions": {
          "type": "string"
        },
        "Firmware Versions": {
          "type": "string"
        },
        "Product URL": {
          "type": "string",
          "format": "uri"
        }
      },
      "required": [
        "Module Name",
        "Standard",
        "Status",
        "Overall Level",
        "Module Type",
        "Embodiment",
        "Description"
      ]
    },
    "Vendor": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "Name": {
          "type": "string"
        },
        "Website": {
          "type": "string",
          "format": "uri"
        },
        "Address": {
          "type": "string"
        },
        "Contacts": {
          "type": "array",
          "minLength": 1,
          "maxLength": 2,
          "items": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
              "Name": {
                "type": "string"
              },
              "Email": {
                "type": "string",
                "format": "email"
              },
              "Phone": {
                "type": "string"
              },
              "Fax": {
                "type": "string"
              }
            },
            "required": [
              "Name",
              "Email"
            ]
          }
        }
      },
      "required": [
        "Name",
        "Website",
        "Address",
        "Contacts"
      ]
    },
    "Related Files": {
      "type": "array",
      "additionalItems": false,
      "items": {
        "type": "array",
        "additionalItems": false,
        "items": [
          {
            "type": "string"
          },
          {
            "type": "string",
            "format": "uri"
          }
        ]
      }
    },
    "Validation History": {
      "type": "array",
      "minItems": 1,
      "additionalItems": false,
      "items": {
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "Date": {
            "type": "string"
          },
          "Type": {
            "type": "string",
            "enum": [
              "Initial",
              "Update"
            ]
          },
          "Lab": {
            "type": "string"
          }
        },
        "required": [
          "Date",
          "Type",
          "Lab"
        ]
      }
    }
  },
  "required": [
    "Certificate Number",
    "Details",
    "Vendor",
    "Related Files",
    "Validation History"
  ]
}

=== ratPoopert/csrc-scraper/tests/cmvp/json/3980.json
{
  "$schema": "./cmvp-certificate.schema.json",
  "Certificate Number": "3980",
  "Details": {
    "Module Name": "Ubuntu 18.04 OpenSSL Cryptographic Module",
    "Standard": "FIPS 140-2",
    "Status": "Active",
    "Sunset Date": "7/11/2026",
    "Overall Level": 1,
    "Caveat": "When operated in FIPS mode. The module generates keys whose strengths are modified by available entropy",
    "Security Level Exceptions": [
      "Physical Security: N/A"
    ],
    "Module Type": "Software",
    "Embodiment": "Multi-Chip Stand Alone",
    "Description": "OpenSSL is an open-source library of various cryptographic algorithms written mainly in C.",
    "Tested Configuration(s)": [
      "Ubuntu 18.04 LTS 64-bit running on Supermicro SYS-5018R-WR with Intel Xeon CPU E5-2620v3 with PAA",
      "Ubuntu 18.04 LTS 64-bit running on Supermicro SYS-5018R-WR with Intel Xeon CPU E5-2620v3 without PAA (single-user mode)"
    ],
    "Approved Algorithms": [
      [
        "AES",
        "Certs. #A817, #A818, #A819, #A825, #A826, #A827, #A828, #A829, #A830, #A831, #A832 and #A833",
        [
          "https://csrc.nist.gov/projects/Cryptographic-Algorithm-Validation-Program/details?source=A&number=817",
          "https://csrc.nist.gov/projects/Cryptographic-Algorithm-Validation-Program/details?source=A&number=818",
          "https://csrc.nist.gov/projects/Cryptographic-Algorithm-Validation-Program/details?source=A&number=819",
          "https://csrc.nist.gov/projects/Cryptographic-Algorithm-Validation-Program/details?source=A&number=825",
          "https://csrc.nist.gov/projects/Cryptographic-Algorithm-Validation-Program/details?source=A&number=826",
          "https://csrc.nist.gov/projects/Cryptographic-Algorithm-Validation-Program/details?source=A&number=827",
          "https://csrc.nist.gov/projects/Cryptographic-Algorithm-Validation-Program/details?source=A&number=828",
          "https://csrc.nist.gov/projects/Cryptographic-Algorithm-Validation-Program/details?source=A&number=829",
          "https://csrc.nist.gov/projects/Cryptographic-Algorithm-Validation-Program/details?source=A&number=830",
          "https://csrc.nist.gov/projects/Cryptographic-Algorithm-Validation-Program/details?source=A&number=831",
          "https://csrc.nist.gov/projects/Cryptographic-Algorithm-Validation-Program/details?source=A&number=832",
          "https://csrc.nist.gov/projects/Cryptographic-Algorithm-Validation-Program/details?source=A&number=833"
        ]
      ],
      [
        "CVL",
        "Certs. #A821, #A822, #A823 and #A824",
        [
          "https://csrc.nist.gov/projects/Cryptographic-Algorithm-Validation-Program/details?source=A&number=821",
          "https://csrc.nist.gov/projects/Cryptographic-Algorithm-Validation-Program/details?source=A&number=822",
          "https://csrc.nist.gov/projects/Cryptographic-Algorithm-Validation-Program/details?source=A&number=823",
          "https://csrc.nist.gov/projects/Cryptographic-Algorithm-Validation-Program/details?source=A&number=824"
        ]
      ],
      [
        "DRBG",
        "Certs. #A817, #A818 and #A819",
        [
          "https://csrc.nist.gov/projects/Cryptographic-Algorithm-Validation-Program/details?source=A&number=817",
          "https://csrc.nist.gov/projects/Cryptographic-Algorithm-Validation-Program/details?source=A&number=818",
          "https://csrc.nist.gov/projects/Cryptographic-Algorithm-Validation-Program/details?source=A&number=819"
        ]
      ],
      [
        "DSA",
        "Certs. #A821, #A822, #A823 and #A824",
        [
          "https://csrc.nist.gov/projects/Cryptographic-Algorithm-Validation-Program/details?source=A&number=821",
          "https://csrc.nist.gov/projects/Cryptographic-Algorithm-Validation-Program/details?source=A&number=822",
          "https://csrc.nist.gov/projects/Cryptographic-Algorithm-Validation-Program/details?source=A&number=823",
          "https://csrc.nist.gov/projects/Cryptographic-Algorithm-Validation-Program/details?source=A&number=824"
        ]
      ],
      [
        "ECDSA",
        "Certs. #A821, #A822, #A823 and #A824",
        [
          "https://csrc.nist.gov/projects/Cryptographic-Algorithm-Validation-Program/details?source=A&number=821",
          "https://csrc.nist.gov/projects/Cryptographic-Algorithm-Validation-Program/details?source=A&number=822",
          "https://csrc.nist.gov/projects/Cryptographic-Algorithm-Validation-Program/details?source=A&number=823",
          "https://csrc.nist.gov/projects/Cryptographic-Algorithm-Validation-Program/details?source=A&number=824"
        ]
      ],
      [
        "HMAC",
        "Certs. #A814, #A815, #A816, #A821, #A822, #A823 and #A824",
        [
          "https://csrc.nist.gov/projects/Cryptographic-Algorithm-Validation-Program/details?source=A&number=814",
          "https://csrc.nist.gov/projects/Cryptographic-Algorithm-Validation-Program/details?source=A&number=815",
          "https://csrc.nist.gov/projects/Cryptographic-Algorithm-Validation-Program/details?source=A&number=816",
          "https://csrc.nist.gov/projects/Cryptographic-Algorithm-Validation-Program/details?source=A&number=821",
          "https://csrc.nist.gov/projects/Cryptographic-Algorithm-Validation-Program/details?source=A&number=822",
          "https://csrc.nist.gov/projects/Cryptographic-Algorithm-Validation-Program/details?source=A&number=823",
          "https://csrc.nist.gov/projects/Cryptographic-Algorithm-Validation-Program/details?source=A&number=824"
        ]
      ],
      [
        "KAS",
        "KAS-SSC Certs. #A821, #A822, #A823, #A824 and #A834, CVL Certs. #A821, #A822, #A823 and #A824",
        []
      ],
      [
        "KTS",
        "AES Certs. #A817, #A818, #A819, #A825, #A826, #A827, #A828, #A829, #A830, #A831, #A832 and #A833; key establishment methodology provides between 128 and 256 bits of encryption strength",
        []
      ],
      [
        "KTS",
        "AES Certs. #A817, #A818 and #A819 and HMAC Certs. #A821, #A822, #A823 and #A824; key establishment methodology provides between 128 or 256 bits of encryption strength",
        []
      ],
      [
        "KTS",
        "Triple-DES Cert. #A820 and HMAC Certs. #A821, #A822, #A823 and #A824; key establishment methodology provides 112 bits of encryption strength",
        []
      ],
      [
        "RSA",
        "Certs. #A821, #A822, #A823 and #A824",
        [
          "https://csrc.nist.gov/projects/Cryptographic-Algorithm-Validation-Program/details?source=A&number=821",
          "https://csrc.nist.gov/projects/Cryptographic-Algorithm-Validation-Program/details?source=A&number=822",
          "https://csrc.nist.gov/projects/Cryptographic-Algorithm-Validation-Program/details?source=A&number=823",
          "https://csrc.nist.gov/projects/Cryptographic-Algorithm-Validation-Program/details?source=A&number=824"
        ]
      ],
      [
        "SHA-3",
        "Certs. #A814, #A815 and #A816",
        [
          "https://csrc.nist.gov/projects/Cryptographic-Algorithm-Validation-Program/details?source=A&number=814",
          "https://csrc.nist.gov/projects/Cryptographic-Algorithm-Validation-Program/details?source=A&number=815",
          "https://csrc.nist.gov/projects/Cryptographic-Algorithm-Validation-Program/details?source=A&number=816"
        ]
      ],
      [
        "SHS",
        "Certs. #A821, #A822, #A823 and #A824",
        [
          "https://csrc.nist.gov/projects/Cryptographic-Algorithm-Validation-Program/details?source=A&number=821",
          "https://csrc.nist.gov/projects/Cryptographic-Algorithm-Validation-Program/details?source=A&number=822",
          "https://csrc.nist.gov/projects/Cryptographic-Algorithm-Validation-Program/details?source=A&number=823",
          "https://csrc.nist.gov/projects/Cryptographic-Algorithm-Validation-Program/details?source=A&number=824"
        ]
      ],
      [
        "Triple-DES",
        "Cert. #A820",
        [
          "https://csrc.nist.gov/projects/Cryptographic-Algorithm-Validation-Program/details?source=A&number=820"
        ]
      ]
    ],
    "Allowed Algorithms": "MD5; NDRNG; RSA (key wrapping; key establishment methodology provides between 112 and 256 bits of encryption strength)",
    "Software Versions": "2.1"
  },
  "Vendor": {
    "Name": "Canonical Ltd.",
    "Website": "http://www.canonical.com",
    "Address": "5th floor, Blue Fin Building\n110 Southwark Street\nLondon SE1 0SU\nUnited Kingdom",
    "Contacts": [
      {
        "Name": "Canonical Certification Team",
        "Email": "security-certifications@lists.canonical.com"
      }
    ]
  },
  "Related Files": [
    [
      "Security Policy",
      "https://csrc.nist.gov/CSRC/media/projects/cryptographic-module-validation-program/documents/security-policies/140sp3980.pdf"
    ],
    [
      "Consolidated Certificate",
      "https://csrc.nist.gov/CSRC/media/projects/cryptographic-module-validation-program/documents/certificates/July%202021_020821_0740_signed.pdf"
    ]
  ],
  "Validation History": [
    {
      "Date": "7/12/2021",
      "Type": "Initial",
      "Lab": "ATSEC INFORMATION SECURITY CORP"
    },
    {
      "Date": "9/21/2021",
      "Type": "Update",
      "Lab": "ATSEC INFORMATION SECURITY CORP"
    },
    {
      "Date": "10/18/2021",
      "Type": "Update",
      "Lab": "ATSEC INFORMATION SECURITY CORP"
    },
    {
      "Date": "11/23/2022",
      "Type": "Update",
      "Lab": "ATSEC INFORMATION SECURITY CORP"
    }
  ]
}

=== ratPoopert/csrc-scraper/tests/examples/cmvp/certificates/json/3189.json
{
  "$schema": "./cmvp-certificate.schema.json",
  "Certificate Number": "3189",
  "Details": {
    "Module Name": "REDCOM Encryption 140-2",
    "Standard": "FIPS 140-2",
    "Status": "Historical",
    "Historical Reason": "SP 800-56Arev3 transition",
    "Overall Level": 1,
    "Caveat": "When operated in FIPS mode. The module generates cryptographic keys whose strengths are modified by available entropy. No assurance of the minimum strength of generated keys",
    "Security Level Exceptions": [
      "Physical Security: N/A"
    ],
    "Module Type": "Software",
    "Embodiment": "Multi-Chip Stand Alone",
    "Description": "REDCOM Encryption 140-2 is a fully FIPS 140-2 validated cryptographic engine for Java and Android based environments. The module delivers core cryptographic functions to these platforms and features robust algorithm support, including Suite B algorithms. REDCOM Encryption 140-2 offloads functions for secure key management, data integrity, data at rest encryption, and secure communications to a trusted implementation. **Oracle and Java are registered trademarks of Oracle and/or its affiliates. **Android is a trademark of Google Inc",
    "Tested Configuration(s)": [
      "CentOS 6 and OpenJDK 1.7 running on HP ProLiant DL360 G7 Server using an Intel Xeon X5670 (single-user mode)"
    ],
    "Approved Algorithms": [
      [
        "AES",
        "Cert. #4702",
        [
          "https://csrc.nist.gov/projects/Cryptographic-Algorithm-Validation-Program/details?source=AES&number=4702"
        ]
      ],
      [
        "CKG",
        "vendor affirmed",
        []
      ],
      [
        "CVL",
        "Certs. #1342, #1343, #1344 and #1345",
        [
          "https://csrc.nist.gov/projects/Cryptographic-Algorithm-Validation-Program/details?source=Component&number=1342",
          "https://csrc.nist.gov/projects/Cryptographic-Algorithm-Validation-Program/details?source=Component&number=1343",
          "https://csrc.nist.gov/projects/Cryptographic-Algorithm-Validation-Program/details?source=Component&number=1344",
          "https://csrc.nist.gov/projects/Cryptographic-Algorithm-Validation-Program/details?source=Component&number=1345"
        ]
      ],
      [
        "DRBG",
        "Cert. #1600",
        [
          "https://csrc.nist.gov/projects/Cryptographic-Algorithm-Validation-Program/details?source=DRBG&number=1600"
        ]
      ],
      [
        "DSA",
        "Cert. #1244",
        [
          "https://csrc.nist.gov/projects/Cryptographic-Algorithm-Validation-Program/details?source=DSA&number=1244"
        ]
      ],
      [
        "ECDSA",
        "Cert. #1160",
        [
          "https://csrc.nist.gov/projects/Cryptographic-Algorithm-Validation-Program/details?source=ECDSA&number=1160"
        ]
      ],
      [
        "HMAC",
        "Cert. #3114",
        [
          "https://csrc.nist.gov/projects/Cryptographic-Algorithm-Validation-Program/details?source=HMAC&number=3114"
        ]
      ],
      [
        "KAS",
        "Cert. #130",
        [
          "https://csrc.nist.gov/projects/Cryptographic-Algorithm-Validation-Program/details?source=KAS&number=130"
        ]
      ],
      [
        "KAS",
        "SP 800-56Arev2, vendor affirmed",
        []
      ],
      [
        "KBKDF",
        "Cert. #145",
        [
          "https://csrc.nist.gov/projects/Cryptographic-Algorithm-Validation-Program/details?source=KDF&number=145"
        ]
      ],
      [
        "KTS",
        "AES Cert. #4702; key establishment methodology provides between 128 and 256 bits of encryption strength",
        []
      ],
      [
        "KTS",
        "SP800-56B, vendor affirmed",
        []
      ],
      [
        "KTS",
        "Triple-DES Cert. #2494; key establishment methodology provides 112 bits of encryption strength",
        []
      ],
      [
        "PBKDF",
        "vendor affirmed",
        []
      ],
      [
        "RSA",
        "Cert. #2562",
        [
          "https://csrc.nist.gov/projects/Cryptographic-Algorithm-Validation-Program/details?source=RSA&number=2562"
        ]
      ],
      [
        "SHA-3",
        "Cert. #24",
        [
          "https://csrc.nist.gov/projects/Cryptographic-Algorithm-Validation-Program/details?source=SHA-3&number=24"
        ]
      ],
      [
        "SHS",
        "Cert. #3849",
        [
          "https://csrc.nist.gov/projects/Cryptographic-Algorithm-Validation-Program/details?source=SHS&number=3849"
        ]
      ],
      [
        "Triple-DES",
        "Cert. #2494",
        [
          "https://csrc.nist.gov/projects/Cryptographic-Algorithm-Validation-Program/details?source=TDES&number=2494"
        ]
      ]
    ],
    "Allowed Algorithms": "Diffie-Hellman (key agreement; key establishment methodology provides 112 bits of encryption strength); MD5; RSA (key wrapping; key establishment methodology provides 112 or 128 bits of encryption strength)",
    "Software Versions": "3.0.1"
  },
  "Vendor": {
    "Name": "REDCOM Laboratories, Inc.",
    "Website": "http://www.redcom.com",
    "Address": "1 Redcom Center\nVictor, NY 14564\nUSA",
    "Contacts": [
      {
        "Name": "Sal Ceravolo",
        "Email": "Sal.Ceravolo@redcom.com",
        "Phone": "585-905-0451"
      },
      {
        "Name": "Chris Hasenauer",
        "Email": "Chris.hasenauer@redcom.com",
        "Phone": "585-905-0451"
      }
    ]
  },
  "Related Files": [
    [
      "Security Policy",
      "https://csrc.nist.gov/CSRC/media/projects/cryptographic-module-validation-program/documents/security-policies/140sp3189.pdf"
    ],
    [
      "Consolidated Certificate",
      "https://csrc.nist.gov/CSRC/media/projects/cryptographic-module-validation-program/documents/certificates/May2018consolidated.pdf"
    ]
  ],
  "Validation History": [
    {
      "Date": "5/31/2018",
      "Type": "Initial",
      "Lab": "UL VERIFICATION SERVICES INC"
    }
  ]
}

=== ratPoopert/csrc-scraper/tests/examples/cmvp/certificates/json/2486.json
{
  "$schema": "./cmvp-certificate.schema.json",
  "Certificate Number": "2486",
  "Details": {
    "Module Name": "Luna速 Backup HSM Cryptographic Module",
    "Standard": "FIPS 140-2",
    "Status": "Historical",
    "Historical Reason": "186-2 transition",
    "Overall Level": 3,
    "Caveat": "When operated in FIPS mode and initialized to Overall Level 3 per Security Policy",
    "Security Level Exceptions": [
      "Mitigation of Other Attacks: N/A"
    ],
    "Module Type": "Hardware",
    "Embodiment": "Multi-Chip Stand Alone",
    "Description": "The Luna速 Backup HSM Hardware Security Module (HSM) provides the same level of security as the Luna速 SA and Luna速 PCI-E HSMs in a convenient, small, low-cost form factor. The Luna Backup HSM ensures that sensitive cryptographic material remains strongly protected in hardware even when not being used. One can easily back up and duplicate keys securely to the Luna Backup HSM for safekeeping in case of emergency, failure or disaster.",
    "Tested Configuration(s)": [
      "N/A"
    ],
    "Approved Algorithms": [
      [
        "AES",
        "Certs. #2664 and #2668",
        [
          "https://csrc.nist.gov/projects/Cryptographic-Algorithm-Validation-Program/details?source=AES&number=2664",
          "https://csrc.nist.gov/projects/Cryptographic-Algorithm-Validation-Program/details?source=AES&number=2668"
        ]
      ],
      [
        "DRBG",
        "Cert. #428",
        [
          "https://csrc.nist.gov/projects/Cryptographic-Algorithm-Validation-Program/details?source=DRBG&number=428"
        ]
      ],
      [
        "DSA",
        "Certs. #804 and #808",
        [
          "https://csrc.nist.gov/projects/Cryptographic-Algorithm-Validation-Program/details?source=DSA&number=804",
          "https://csrc.nist.gov/projects/Cryptographic-Algorithm-Validation-Program/details?source=DSA&number=808"
        ]
      ],
      [
        "ECDSA",
        "Certs. #461 and #464",
        [
          "https://csrc.nist.gov/projects/Cryptographic-Algorithm-Validation-Program/details?source=ECDSA&number=461",
          "https://csrc.nist.gov/projects/Cryptographic-Algorithm-Validation-Program/details?source=ECDSA&number=464"
        ]
      ],
      [
        "HMAC",
        "Certs. #1655 and #1659",
        [
          "https://csrc.nist.gov/projects/Cryptographic-Algorithm-Validation-Program/details?source=HMAC&number=1655",
          "https://csrc.nist.gov/projects/Cryptographic-Algorithm-Validation-Program/details?source=HMAC&number=1659"
        ]
      ],
      [
        "KAS",
        "Cert. #44",
        [
          "https://csrc.nist.gov/projects/Cryptographic-Algorithm-Validation-Program/details?source=KAS&number=44"
        ]
      ],
      [
        "KBKDF",
        "Cert. #15",
        [
          "https://csrc.nist.gov/projects/Cryptographic-Algorithm-Validation-Program/details?source=KDF&number=15"
        ]
      ],
      [
        "RSA",
        "Certs. #1369 and #1372",
        [
          "https://csrc.nist.gov/projects/Cryptographic-Algorithm-Validation-Program/details?source=RSA&number=1369",
          "https://csrc.nist.gov/projects/Cryptographic-Algorithm-Validation-Program/details?source=RSA&number=1372"
        ]
      ],
      [
        "SHS",
        "Certs. #2237 and #2241",
        [
          "https://csrc.nist.gov/projects/Cryptographic-Algorithm-Validation-Program/details?source=SHS&number=2237",
          "https://csrc.nist.gov/projects/Cryptographic-Algorithm-Validation-Program/details?source=SHS&number=2241"
        ]
      ],
      [
        "Triple-DES",
        "Certs. #1598 and #1600",
        [
          "https://csrc.nist.gov/projects/Cryptographic-Algorithm-Validation-Program/details?source=TDES&number=1598",
          "https://csrc.nist.gov/projects/Cryptographic-Algorithm-Validation-Program/details?source=TDES&number=1600"
        ]
      ],
      [
        "Triple-DES MAC",
        "Triple-DES Certs. #1598 and #1600, vendor affirmed",
        []
      ]
    ],
    "Other Algorithms": "Diffie-Hellman (key agreement; key establishment methodology provides 112 or 128 bits of encryption strength; non-compliant less than 112 bits of encryption strength); EC Diffie-Hellman (key agreement; key establishment methodology provides 112 or 128 bits of encryption strength); HRNG",
    "Hardware Versions": "LTK-03, Version Code 0102",
    "Firmware Versions": "6.10.7, 6.10.9, and 6.11.2"
  },
  "Vendor": {
    "Name": "SafeNet Assured Technologies, LLC",
    "Website": "",
    "Address": "Suite D, 3465 Box Hill Corporate Center Drive\nAbingdon, Maryland 21009\nUSA",
    "Contacts": [
      {
        "Name": "Shawn Campbell",
        "Email": "shawn.campbell@safenetat.com",
        "Phone": "443-484-7075"
      },
      {
        "Name": "Bill Becker",
        "Email": "bill.becker@safenetat.com",
        "Phone": "443-484-7075"
      }
    ]
  },
  "Related Files": [
    [
      "Security Policy",
      "https://csrc.nist.gov/CSRC/media/projects/cryptographic-module-validation-program/documents/security-policies/140sp2486.pdf"
    ],
    [
      "Consolidated Certificate",
      "https://csrc.nist.gov/CSRC/media/projects/cryptographic-module-validation-program/documents/certificates/FIPS140ConsolidatedCertDec2015.pdf"
    ]
  ],
  "Validation History": [
    {
      "Date": "12/15/2015",
      "Type": "Initial",
      "Lab": "EWA CANADA"
    },
    {
      "Date": "11/20/2017",
      "Type": "Update",
      "Lab": "EWA CANADA"
    },
    {
      "Date": "3/27/2018",
      "Type": "Update",
      "Lab": "EWA CANADA"
    },
    {
      "Date": "5/24/2018",
      "Type": "Update",
      "Lab": "EWA CANADA"
    }
  ]
}
